<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_testsuite_excel005</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ea3128d6-f71c-46bd-9898-a81c2cbffb48</testSuiteGuid>
   <testCaseLink>
      <guid>d53aff43-bb7f-4c44-a959-0501d17c3b4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Amazon_testcase_005</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b4b0be52-dead-436a-8571-f5da60d671ce</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_excel005</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b4b0be52-dead-436a-8571-f5da60d671ce</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>f16f0da5-16ea-4f79-83ea-3e697870177c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b4b0be52-dead-436a-8571-f5da60d671ce</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Input</value>
         <variableId>a80b81e9-cb67-4fb0-af20-450d8a8e4dcb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
