<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or enter an Indian pincode_GLUXZipUpd_df256c</name>
   <tag></tag>
   <elementGuidId>24c9bd01-1570-49e2-a4ee-245964baff84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GLUXZipUpdateInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GLUXZipUpdateInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c10887c7-146f-403e-add1-5f07086cceb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GLUX_Full_Width a-declarative</value>
      <webElementGuid>bafe222f-104f-4d81-bf50-1112305a8ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e0e26f3e-b2c4-4294-bb5c-ec65ca42f9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>d49b0fa7-4232-4123-8cdf-0a167d3941bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>500056</value>
      <webElementGuid>096d397c-4382-4cfe-b1c9-e3dfa722407e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GLUXZipUpdateInput</value>
      <webElementGuid>519a895f-de36-4519-8d79-802b41baa8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>or enter an Indian pincode</value>
      <webElementGuid>bcc31344-3b4c-4bfc-9204-126cdcff548b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>GLUXPostalInputAction</value>
      <webElementGuid>bc12c764-5ccd-4f96-8dae-5458f00eea1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GLUXZipUpdateInput&quot;)</value>
      <webElementGuid>e69d39b6-68b2-45fd-9209-68ec557a06fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GLUXZipUpdateInput']</value>
      <webElementGuid>b58e4b1f-7af3-4afb-9dab-0c77431898ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GLUXZipInputSection']/div/input</value>
      <webElementGuid>2c2d888d-fbc6-46f2-bdbb-ed0bbcf7270c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>8d3330e5-c355-47ad-a464-a838d55fef09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GLUXZipUpdateInput']</value>
      <webElementGuid>0c37444a-9a00-4786-b942-5a83a9079544</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
